# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty32"
  config.vm.network :private_network, ip: "192.168.68.8"

  config.vm.provision "shell", :path => "provision/bootstrap.sh"
end
